var categories = [
      { id:'Period Pieces'},
      { id:'Kristen Stewart Being Gay'},
      { id:'Chill and Fun'},
      { id:'Slow Beautiful Hot Foreign'},
      { id:'"Totally" "Not" "Gay"'},
      { id:'RomCom'},
      { id:'High School'},
      { id:'Starring Women of Color'},
      { id:'SO 90s'},
      { id:'Pre-90s'},
      { id:'Lesbian Serial Killers'},
      { id:'Death and Destruction'},
      { id:'Religious Turmoil'},
      { id:'Butch'},
      { id:'Campy'},
      { id:'Sports'},
      { id:'Student/Teacher'},
      { id:'Small Town USA'},
      { id:'So Bad It Made Me Mad', title: 'Movies directly linked to "So Bad" are not worth seeing but are worth knowing and complaining about. <br> Movies with a dashed line to So Bad are worth watching, it just might not be fun.'},
    ];
